void main() {
  // collection örneği :
  List list = [];
  list.add("1");
  list.add("2");
  list.add("3");
  list.add("4");
  list.add("5");
  list.add("6");
  list.add("7");
  list.add("8");
  list.add("9");
  list.add("10");
  print(list);
  list.remove("1");
  print(list);
  list.removeAt(0);
  print(list);
  list.removeLast();
  print(list);
  list.removeRange(0, 3);
  print(list);
  list.insert(0, "1");
  print(list);
  list.insertAll(0, ["2", "3", "4"]);
  print(list);
  list.replaceRange(0, 3, ["1", "2", "3"]);
  print(list);
  list.fillRange(0, 3, "1");
  print(list);
  list.fillRange(0, 3, "2");
  print(list);
  list.fillRange(0, 3, "3");
  print(list);
  list.fillRange(0, 3, "4");
  print(list);
  list.fillRange(0, 3, "5");
  print(list);
  list.fillRange(0, 3, "6");
  print(list);
  list.fillRange(0, 3, "7");
  print(list);
  list.fillRange(0, 3, "8");
  print(list);
  list.fillRange(0, 3, "9");
  print(list);
  list.fillRange(0, 3, "10");
  print(list);
  list.addAll(["1", "2", "3"]);
  print(list);
  list.removeWhere((element) => element == "1");
  print(list);
  list.removeWhere((element) => element == "2");
  print(list);
  list.removeWhere((element) => element == "3");
  print(list);
  list.removeWhere((element) => element == "4");
  print(list);
  list.removeWhere((element) => element == "5");
  print(list);
  list.removeWhere((element) => element == "6");
  print(list);
  list.removeWhere((element) => element == "7");
  print(list);
  list.removeWhere((element) => element == "8");
  print(list);
  list.removeWhere((element) => element == "9");
}
